import mongoose from 'mongoose';
import axios from 'axios';
import {
  Order,
  IOrder,
  OrderType,
  OrderStatus,
} from '../../models/Order.model';
import { LPOCampaign, CampaignStatus } from '../../models/LPOCampaign.model';
import { User, UserRole } from '../../models/User.model';
import { env } from '../../config/env';
import { generateOtp, verifyOtp, otpExpiresAt } from '../../utils/otp';
import { calculateTransportFee } from '../../utils/financialMath';
import { initiateDispatch } from '../dispatch/dispatch.service';
import { pingVendor } from '../../sockets/namespaces/vendor.namespace';
import { AppError } from '../../middleware/errorHandler.middleware';
import { logger } from '../../utils/logger';
import { VehicleClass } from '../../models/User.model';

// ─── Google Distance Matrix ───────────────────────────────────────────────────

interface DistanceMatrixResult {
  distanceKm: number;
  durationMinutes: number;
}

const getDistanceFromGoogle = async (
  origin: [number, number],
  destination: [number, number]
): Promise<DistanceMatrixResult> => {
  const response = await axios.get(
    'https://maps.googleapis.com/maps/api/distancematrix/json',
    {
      params: {
        origins: `${origin[1]},${origin[0]}`,
        destinations: `${destination[1]},${destination[0]}`,
        key: env.GOOGLE_MAPS_API_KEY,
        units: 'metric',
      },
      timeout: 10_000,
    }
  );

  const element = response.data?.rows?.[0]?.elements?.[0];

  if (!element || element.status !== 'OK') {
    throw new AppError(
      'Could not calculate distance between locations.',
      502,
      'DISTANCE_MATRIX_FAILED'
    );
  }

  return {
    distanceKm: element.distance.value / 1000,
    durationMinutes: Math.ceil(element.duration.value / 60),
  };
};

// ─── OTP Dispatch (Tri-Party Security Model) ──────────────────────────────────

/**
 * SECURITY INVARIANT — enforced throughout this module:
 *
 * OTP 1 (Loading/Pickup):
 * Generated by system → sent ONLY to Farmer (B2B) or Vendor (B2C).
 * The driver NEVER receives OTP 1. They input it after the farmer dictates it.
 *
 * OTP 2 (Delivery):
 * Generated by system → sent ONLY to Buyer/Consumer.
 * The driver NEVER receives OTP 2. They input it after the buyer dictates it.
 *
 * This physical handshake proves presence at both locations.
 * Any code path that returns an OTP to a TRANSPORTER role is a security violation.
 */

/**
 * Sends OTP 1 to the source party (Farmer or Vendor).
 * Stubbed for Sprint 8 — Africa's Talking SMS client will replace the stub.
 */
const sendLoadingOtpToSourceParty = async (
  recipientPhone: string,
  recipientName: string,
  rawOtp: string,
  orderId: string
): Promise<void> => {
  const shortOrderRef = orderId.slice(-6).toUpperCase();
  const message =
    `Akripesa: Your pickup verification code for order #${shortOrderRef} ` +
    `is ${rawOtp}. Dictate this to the driver when they arrive. Do not share via SMS/WhatsApp.`;

  if (env.NODE_ENV !== 'production') {
    // DEVELOPMENT ONLY — never log OTPs in production
    logger.debug(
      `[OTP STUB - SOURCE] Recipient: ${recipientPhone} (${recipientName}) | ` +
      `Order: ${orderId} | OTP: ${rawOtp}`
    );
    return;
  }

  // Sprint 8: await atSmsClient.send({ to: recipientPhone, message });
  logger.info(
    `Loading OTP dispatched to source party ${recipientPhone} for order ${orderId}.`
  );
};

/**
 * Sends OTP 2 to the destination party (Buyer or Consumer).
 * Stubbed for Sprint 8.
 */
const sendDeliveryOtpToBuyerParty = async (
  recipientPhone: string,
  recipientName: string,
  rawOtp: string,
  orderId: string
): Promise<void> => {
  const shortOrderRef = orderId.slice(-6).toUpperCase();
  const message =
    `Akripesa: Your delivery confirmation code for order #${shortOrderRef} ` +
    `is ${rawOtp}. Dictate this to the driver upon receipt of goods. Do not share via SMS/WhatsApp.`;

  if (env.NODE_ENV !== 'production') {
    logger.debug(
      `[OTP STUB - BUYER] Recipient: ${recipientPhone} (${recipientName}) | ` +
      `Order: ${orderId} | OTP: ${rawOtp}`
    );
    return;
  }

  // Sprint 8: await atSmsClient.send({ to: recipientPhone, message });
  logger.info(
    `Delivery OTP dispatched to buyer party ${recipientPhone} for order ${orderId}.`
  );
};

// ─── Order Creation ───────────────────────────────────────────────────────────

export const createB2BOrder = async (
  dto: { campaignId: string },
  adminUserId: string
): Promise<IOrder> => {
  const session = await mongoose.startSession();
  session.startTransaction();

  try {
    const campaign = await LPOCampaign.findById(dto.campaignId)
      .select('+internalData')
      .session(session)
      .exec();

    if (!campaign) {
      throw new AppError('Campaign not found.', 404, 'CAMPAIGN_NOT_FOUND');
    }

    if (campaign.status !== CampaignStatus.FULLY_FUNDED) {
      throw new AppError(
        `Cannot create order for campaign with status: ${campaign.status}`,
        400,
        'CAMPAIGN_NOT_FULLY_FUNDED'
      );
    }

    let vehicleClass = VehicleClass.FRR_TRUCK;
    if (campaign.quantityKg <= 500) vehicleClass = VehicleClass.PICKUP;
    else if (campaign.quantityKg <= 3000) vehicleClass = VehicleClass.CANTER;

    const { distanceKm } = await getDistanceFromGoogle(
      campaign.pickupLocation.coordinates,
      campaign.deliveryLocation.coordinates
    );

    const transportFeeKes = calculateTransportFee(distanceKm, vehicleClass);

    // ── Generate OTPs ─────────────────────────────────────────────────────────
    const { rawOtp: rawLoadingOtp, hashedOtp: hashedLoadingOtp } = generateOtp();
    const { rawOtp: rawDeliveryOtp, hashedOtp: hashedDeliveryOtp } = generateOtp();
    // rawOtps are held in memory only within this function scope.
    // They are dispatched to the source/buyer parties below.
    // They are NEVER written to the Order document, Redis, or any response body.

    const farmerSplits = campaign.farmerAllocations.map((fa) => ({
      recipientId: fa.farmerId,
      recipientRole: 'FARMER' as const,
      amountKes: fa.allocatedAmountKes,
      isPaid: false,
    }));

    const [order] = await Order.create(
      [
        {
          orderType: OrderType.B2B_SUPPLY_CHAIN,
          status: OrderStatus.ESCROW_LOCKED,
          campaignId: campaign._id,
          buyerId: campaign.createdBy,
          commodity: campaign.commodity,
          quantityKg: campaign.quantityKg,
          totalOrderValueKes: campaign.internalData.contractValue,
          transportFeeKes,
          platformFeeKes:
            campaign.internalData.contractValue -
            campaign.currentFundedAmountKes -
            transportFeeKes,
          paymentSplits: [
            ...farmerSplits,
            {
              recipientId: new mongoose.Types.ObjectId(adminUserId),
              recipientRole: 'PLATFORM' as const,
              amountKes:
                campaign.internalData.contractValue -
                campaign.currentFundedAmountKes -
                transportFeeKes,
              isPaid: false,
            },
          ],
          pickupLocation: {
            type: 'Point',
            coordinates: campaign.pickupLocation.coordinates,
            address: campaign.pickupLocation.address,
          },
          deliveryLocation: {
            type: 'Point',
            coordinates: campaign.deliveryLocation.coordinates,
            address: campaign.deliveryLocation.address,
          },
          distanceKm,
          // Only hashed OTPs stored in DB — raw values never persisted
          loadingOtp: {
            otp: hashedLoadingOtp,
            isUsed: false,
            expiresAt: otpExpiresAt(120), // 2 hours
          },
          deliveryOtp: {
            otp: hashedDeliveryOtp,
            isUsed: false,
            expiresAt: otpExpiresAt(240), // 4 hours
          },
          escrowLockedAt: new Date(),
        },
      ],
      { session }
    );

    await LPOCampaign.findByIdAndUpdate(
      campaign._id,
      { status: CampaignStatus.LOCKED_IN_TRANSIT },
      { session }
    );

    await session.commitTransaction();

    // ── Dispatch OTP 1 to each Farmer (source parties) ───────────────────────
    // Happens AFTER transaction commits. Failures here are logged but do not
    // roll back the order — admin can resend via dashboard.
    for (const allocation of campaign.farmerAllocations) {
      try {
        const farmer = await User.findById(allocation.farmerId)
          .select('phoneNumber fullName')
          .exec();

        if (farmer) {
          await sendLoadingOtpToSourceParty(
            farmer.phoneNumber,
            farmer.fullName,
            rawLoadingOtp,
            order._id.toString()
          );
        }
      } catch (smsErr) {
        logger.error(
          `Failed to send loading OTP to farmer ${allocation.farmerId}: ${smsErr}`
        );
      }
    }

    // ── Dispatch OTP 2 to Buyer ───────────────────────────────────────────────
    // Sent NOW so buyer has it ready when the truck arrives.
    try {
      const buyer = await User.findById(campaign.createdBy)
        .select('phoneNumber fullName')
        .exec();

      if (buyer) {
        await sendDeliveryOtpToBuyerParty(
          buyer.phoneNumber,
          buyer.fullName,
          rawDeliveryOtp,
          order._id.toString()
        );
      }
    } catch (smsErr) {
      logger.error(`Failed to send delivery OTP to buyer: ${smsErr}`);
    }

    // ── Initiate dispatch ─────────────────────────────────────────────────────
    await Order.findByIdAndUpdate(order._id, {
      status: OrderStatus.AWAITING_DISPATCH,
    });
    await initiateDispatch(order);

    // rawLoadingOtp and rawDeliveryOtp go out of scope here.
    // They are not in the returned order document.
    return order;
  } catch (err) {
    await session.abortTransaction();
    throw err;
  } finally {
    session.endSession();
  }
};

// ─── OTP Verification ─────────────────────────────────────────────────────────

/**
 * SECURITY NOTE on both verify functions:
 *
 * The caller is always a TRANSPORTER. The response returned to them
 * contains only order status and logistical fields.
 * OTP fields are selected for server-side verification only and are
 * NEVER included in the returned object or any API response body.
 * The controller enforces this by using a field-stripped projection.
 */

export const verifyLoadingOtp = async (
  orderId: string,
  driverId: string,
  candidateOtp: string
): Promise<{ orderId: string; status: OrderStatus; loadedAt: Date }> => {
  // Explicitly select OTP hash for server-side comparison only
  const order = await Order.findById(orderId)
    .select('+loadingOtp.otp +deliveryOtp.otp')
    .exec();

  if (!order) {
    throw new AppError('Order not found.', 404, 'ORDER_NOT_FOUND');
  }

  if (order.assignedDriverId?.toString() !== driverId) {
    throw new AppError(
      'You are not the assigned driver for this order.',
      403,
      'DRIVER_MISMATCH'
    );
  }

  if (order.status !== OrderStatus.DRIVER_ASSIGNED) {
    throw new AppError(
      `Cannot verify loading OTP for order in status: ${order.status}`,
      400,
      'INVALID_ORDER_STATUS'
    );
  }

  if (order.loadingOtp.isUsed) {
    throw new AppError('Loading OTP has already been used.', 409, 'OTP_ALREADY_USED');
  }

  if (new Date() > order.loadingOtp.expiresAt) {
    throw new AppError('Loading OTP has expired.', 410, 'OTP_EXPIRED');
  }

  // Server-side hash comparison — candidate OTP hashed, compared via timingSafeEqual
  const isValid = verifyOtp(candidateOtp, order.loading.otp);

  if (!isValid) {
    // Log failed attempts for fraud monitoring (never log the candidate OTP itself)
    logger.warn(
      `Invalid loading OTP attempt | Order: ${orderId} | Driver: ${driverId}`
    );
    throw new AppError('Invalid OTP. Please ask the farmer to confirm the code.', 401, 'OTP_INVALID');
  }

  const loadedAt = new Date();

  await Order.findByIdAndUpdate(orderId, {
    status: OrderStatus.IN_TRANSIT,
    'loadingOtp.isUsed': true,
    'loadingOtp.usedAt': loadedAt,
    loadedAt,
  });

  logger.info(`Loading OTP verified | Order: ${orderId} | Driver: ${driverId}`);

  // Notify tracking room — order now IN_TRANSIT
  // NOTE: getIO() must be imported in actual file if uncommented, leaving standard logic intact.
  const ioGlobal: any = global;
  if (ioGlobal.getIO) {
    ioGlobal.getIO()
      .of('/tracking')
      .to(`order:${orderId}`)
      .emit('tracking:in_transit', {
        orderId,
        loadedAt: loadedAt.toISOString(),
      });
  }

  // Return ONLY logistical fields — no OTP data in response
  return { orderId, status: OrderStatus.IN_TRANSIT, loadedAt };
};

export const verifyDeliveryOtp = async (
  orderId: string,
  driverId: string,
  candidateOtp: string
): Promise<{ orderId: string; status: OrderStatus; deliveredAt: Date }> => {
  const order = await Order.findById(orderId)
    .select('+loadingOtp.otp +deliveryOtp.otp')
    .exec();

  if (!order) {
    throw new AppError('Order not found.', 404, 'ORDER_NOT_FOUND');
  }

  if (order.assignedDriverId?.toString() !== driverId) {
    throw new AppError(
      'You are not the assigned driver for this order.',
      403,
      'DRIVER_MISMATCH'
    );
  }

  if (order.status !== OrderStatus.IN_TRANSIT) {
    throw new AppError(
      `Cannot verify delivery OTP for order in status: ${order.status}`,
      400,
      'INVALID_ORDER_STATUS'
    );
  }

  if (order.deliveryOtp.isUsed) {
    throw new AppError('Delivery OTP has already been used.', 409, 'OTP_ALREADY_USED');
  }

  if (new Date() > order.deliveryOtp.expiresAt) {
    throw new AppError('Delivery OTP has expired.', 410, 'OTP_EXPIRED');
  }

  const isValid = verifyOtp(candidateOtp, order.deliveryOtp.otp);

  if (!isValid) {
    logger.warn(
      `Invalid delivery OTP attempt | Order: ${orderId} | Driver: ${driverId}`
    );
    throw new AppError('Invalid OTP. Please ask the buyer to confirm the code.', 401, 'OTP_INVALID');
  }

  const deliveredAt = new Date();

  await Order.findByIdAndUpdate(orderId, {
    status: OrderStatus.DELIVERED,
    'deliveryOtp.isUsed': true,
    'deliveryOtp.usedAt': deliveredAt,
    deliveredAt,
  });

  // Re-enable driver
  await User.findByIdAndUpdate(driverId, {
    'transporterProfile.isAvailable': true,
  });

  logger.info(`Delivery OTP verified | Order: ${orderId} | Driver: ${driverId}`);

  // Notify tracking room — order DELIVERED
  const ioGlobal: any = global;
  if (ioGlobal.getIO) {
    ioGlobal.getIO()
      .of('/tracking')
      .to(`order:${orderId}`)
      .emit('tracking:delivered', {
        orderId,
        deliveredAt: deliveredAt.toISOString(),
      });
  }

  // Transition B2B campaign to AWAITING_SETTLEMENT
  if (order.orderType === OrderType.B2B_SUPPLY_CHAIN && order.campaignId) {
    await LPOCampaign.findByIdAndUpdate(order.campaignId, {
      status: CampaignStatus.AWAITING_SETTLEMENT,
    });
    logger.info(
      `Campaign ${order.campaignId} → AWAITING_SETTLEMENT after delivery.`
    );
  }

  // Return ONLY logistical fields — no OTP data in response
  return { orderId, status: OrderStatus.DELIVERED, deliveredAt };
};

// ─── NEW ADMIN SERVICES ADDED BELOW ─────────────────────────────────────────

/**
 * Admin: Fetch all active orders for the Logistics Command Center.
 * "Active" means any order not yet SETTLED or CANCELLED.
 */
export const getActiveOrdersForAdmin = async (): Promise<IOrder[]> => {
  return Order.find({
    status: {
      $nin: [OrderStatus.SETTLED, OrderStatus.CANCELLED],
    },
  })
    .sort({ createdAt: -1 })
    .lean()
    .exec() as Promise<IOrder[]>;
};

/**
 * Admin: Manually re-triggers dispatch for an AWAITING_DRIVER order.
 * Resets the dispatch attempt list and restarts the cascade from
 * the initial radius for the order's vehicle class.
 */
export const rerouteOrder = async (orderId: string): Promise<IOrder> => {
  const order = await Order.findById(orderId).exec();

  if (!order) {
    throw new AppError('Order not found.', 404, 'ORDER_NOT_FOUND');
  }

  if (order.status !== OrderStatus.AWAITING_DRIVER) {
    throw new AppError(
      `Only AWAITING_DRIVER orders can be re-routed. Current status: ${order.status}`,
      400,
      'INVALID_STATUS_FOR_REROUTE'
    );
  }

  // Clear all previous dispatch attempts so excluded driver list resets.
  // Admin manual re-route gives ALL drivers a fresh chance — the previous
  // cascade may have been exhausted due to a temporary unavailability spike.
  const updatedOrder = await Order.findByIdAndUpdate(
    orderId,
    {
      status: OrderStatus.AWAITING_DISPATCH,
      dispatchAttempts: [],
    },
    { new: true }
  ).exec();

  // Re-enable any driver that was left in isAvailable: false
  // from a timed-out offer that was never cleaned up
  await User.updateMany(
    { role: UserRole.TRANSPORTER, 'transporterProfile.isAvailable': false },
    { 'transporterProfile.isAvailable': true }
  );

  // Restart cascade from scratch
  await initiateDispatch(updatedOrder!);

  logger.info(
    `Order ${orderId} manually re-routed by admin. Dispatch cascade restarted.`
  );

  return updatedOrder!;
};